wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.22.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1761443299
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      2:
      - 1
      - 5
      - 41
      - 53
      3:
      - 13
      - 16
      - 42
      4: 3.10.12
      5: 0.22.2
      13: linux-x86_64
    e:
      4x7hcz07dafd9md5g2zc0gublgz4r9ax:
        os: Linux-5.15.0-156-generic-x86_64-with-glibc2.35
        python: CPython 3.10.12
        started_at: '2025-10-26T01:48:19.548437Z'
        args:
        - train
        - --exp_name
        - tusimple_fast
        - --cfg
        - cfgs/laneatt_tusimple_split_resnet18.yml
        program: /home/bozhen2/ComputerVision/lanetatt-classproject/external/LaneATT/main.py
        code_path: main.py
        code_path_local: main.py
        git:
          remote_url: https://github.com/lucastabelini/LaneATT
          commit: 2f8583ba14eccba05e6779668bc3a38bc751984a
        email: bozhen2@illinois.edu
        root: /home/bozhen2/ComputerVision/lanetatt-classproject/external/LaneATT
        host: anastasio-wk-02.bioen.illinois.edu
        executable: /home/bozhen2/.cache/pypoetry/virtualenvs/laneatt-classproj-TAaFv3Zi-py3.10/bin/python
        cpu_count: 10
        cpu_count_logical: 20
        gpu_type: NVIDIA RTX 4500 Ada Generation
        gpu_count: 1
        disk:
          /:
            total: '491290001408'
            used: '44720443392'
        memory:
          total: '134268522496'
        gpu_nvidia:
        - name: NVIDIA RTX 4500 Ada Generation
          memory_total: '25763512320'
          cuda_cores: 7680
          architecture: Ada
          uuid: GPU-a82a3482-87c0-9b33-9b29-b9c3ca167b20
        cuda_version: '12.2'
        writer_id: 4x7hcz07dafd9md5g2zc0gublgz4r9ax
config:
  desc: null
  value:
    val_every: 10
    model_checkpoint_interval: 1
    seed: 0
    model:
      name: LaneATT
      parameters:
        backbone: resnet18
        S: 72
        topk_anchors: 1000
        anchors_freq_path: data/tusimple_anchors_freq.pt
        img_h: 360
        img_w: 640
    batch_size: 16
    epochs: 21
    loss_parameters: {}
    train_parameters:
      conf_threshold: null
      nms_thres: 15.0
      nms_topk: 3000
    test_parameters:
      conf_threshold: 0.2
      nms_thres: 45.0
      nms_topk: 5
    optimizer:
      name: Adam
      parameters:
        lr: 0.0003
    lr_scheduler:
      name: CosineAnnealingLR
      parameters:
        T_max: 45400
    datasets:
      train:
        type: LaneDataset
        parameters:
          S: 72
          dataset: tusimple
          split: train
          img_size:
          - 360
          - 640
          max_lanes: 5
          normalize: false
          aug_chance: 1.0
          augmentations:
          - name: Affine
            parameters:
              translate_px:
                x:
                - -25
                - 25
                y:
                - -10
                - 10
              rotate:
              - -6
              - 6
              scale:
              - 0.85
              - 1.15
          - name: HorizontalFlip
            parameters:
              p: 0.5
          root: datasets/tusimple
      val:
        type: LaneDataset
        parameters:
          S: 72
          dataset: tusimple
          split: val
          img_size:
          - 360
          - 640
          max_lanes: 5
          normalize: false
          aug_chance: 0
          augmentations: null
          root: datasets/tusimple
      test:
        type: LaneDataset
        parameters:
          S: 72
          dataset: tusimple
          split: val
          img_size:
          - 360
          - 640
          max_lanes: 5
          normalize: false
          aug_chance: 0
          augmentations: null
          root: datasets/tusimple
config_str:
  desc: null
  value: "# ===============================================================\n# LaneATT\
    \ - TuSimple (custom split version)\n# ===============================================================\n\
    \nval_every: 10\nmodel_checkpoint_interval: 1\nseed: 0\n\nmodel:\n  name: LaneATT\n\
    \  parameters:\n    backbone: resnet18\n    S: &S 72\n    topk_anchors: 1000\n\
    \    anchors_freq_path: 'data/tusimple_anchors_freq.pt'\n    img_h: &img_h 360\n\
    \    img_w: &img_w 640\n\nbatch_size: 16\nepochs: 21\nloss_parameters: {}\n\n\
    train_parameters:\n  conf_threshold:\n  nms_thres: 15.\n  nms_topk: 3000\n\ntest_parameters:\n\
    \  conf_threshold: 0.2\n  nms_thres: 45.\n  nms_topk: &max_lanes 5\n\noptimizer:\n\
    \  name: Adam\n  parameters:\n    lr: 0.0003\n\nlr_scheduler:\n  name: CosineAnnealingLR\n\
    \  parameters:\n    T_max: 45400  # 100 * 454 iterations\n\n# ===============================================================\n\
    # Dataset (Custom split: train/val)\n# ===============================================================\n\
    datasets:\n  train: &train\n    type: LaneDataset\n    parameters:\n      S: *S\n\
    \      dataset: tusimple\n      split: train\n      img_size: [*img_h, *img_w]\n\
    \      max_lanes: *max_lanes\n      normalize: false\n      aug_chance: 1.0\n\
    \      augmentations:\n        - name: Affine\n          parameters:\n       \
    \     translate_px:\n              x: !!python/tuple [-25, 25]\n             \
    \ y: !!python/tuple [-10, 10]\n            rotate: !!python/tuple [-6, 6]\n  \
    \          scale: !!python/tuple [0.85, 1.15]\n        - name: HorizontalFlip\n\
    \          parameters:\n            p: 0.5\n      root: \"datasets/tusimple\"\n\
    \n  val:\n    type: LaneDataset\n    parameters:\n      S: *S\n      dataset:\
    \ tusimple\n      split: val\n      img_size: [*img_h, *img_w]\n      max_lanes:\
    \ *max_lanes\n      normalize: false\n      aug_chance: 0\n      augmentations:\n\
    \      root: \"datasets/tusimple\"\n\n  test:\n    type: LaneDataset\n    parameters:\n\
    \      S: *S\n      dataset: tusimple\n      split: val        # \U0001F448 或者\
    \ test，如果你有 test_label.json\n      img_size: [*img_h, *img_w]\n      max_lanes:\
    \ *max_lanes\n      normalize: false\n      aug_chance: 0\n      augmentations:\n\
    \      root: \"datasets/tusimple\"\n"
